workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      groups:
        - firebase_credentials
    scripts:
      - name: Install dependencies
        script: flutter pub get
      
      - name: Build iOS
        script: flutter build ios --release
      
      - name: Create IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app_ponto.ipa Payload
          mv app_ponto.ipa ../../../
    artifacts:
      - build/ios/ipa/*.ipa
      - app_ponto.ipa
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: "1:331527965536:ios:709b70726dc23c6a2fec05"
          groups: 
            - "iosTesters"