name: app_ponto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.0.0

  # 📍 Localização
  geolocator: ^12.0.0
  geocoding: ^4.0.0

  # 🗺️ Mapa Gratuito (OpenStreetMap)
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # 📱 Utilitários Mobile
  local_auth: ^2.1.6
  camera: ^0.10.5
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # 🎨 Interface
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # 📦 Utilitários Gerais
  image_picker: ^1.0.4
  url_launcher: ^6.2.5
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  provider: ^6.1.5+1
  dio: ^5.9.2

  # 📊 Excel
  excel: ^4.0.0

  # 🌐 Universal HTML (substitui o dart:html)
  universal_html: ^2.2.3

  # 📁 Compartilhamento e Arquivos (para Mobile/Desktop)
  share_plus: ^12.0.2
  path_provider: ^2.1.6

  # 🌐 Internacionalização
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true