// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzQyNLEcSMv8y1KGl1jn76KL-k-SUMjM',
    appId: '1:331527965536:web:f5948245084a119f2fec05',
    messagingSenderId: '331527965536',
    projectId: 'app-ponto-ggc',
    authDomain: 'app-ponto-ggc.firebaseapp.com',
    storageBucket: 'app-ponto-ggc.firebasestorage.app',
    measurementId: 'G-5W3FKN9XFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4rX9F_WZeFtro9Djh7qnDiz2y21KV1T4',
    appId: '1:331527965536:android:39d8cc095f6152f62fec05',
    messagingSenderId: '331527965536',
    projectId: 'app-ponto-ggc',
    storageBucket: 'app-ponto-ggc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGzQyNLEcSMv8y1KGl1jn76KL-k-SUMjM',
    appId: '1:331527965536:web:e3f1c238b9de028e2fec05',
    messagingSenderId: '331527965536',
    projectId: 'app-ponto-ggc',
    authDomain: 'app-ponto-ggc.firebaseapp.com',
    storageBucket: 'app-ponto-ggc.firebasestorage.app',
    measurementId: 'G-T5R9Q5897Y',
  );
}
